name: fake_async
version: 0.1.0
author: Sean Eagan <seaneagan1@gmail.com>
description: Simulates the asynchronous advancement of time and the microtask queue in order to make units which depend on timers and microtasks testable.
homepage: http://github.com/seaneagan/fake_async
dependencies:
  unittest: any
